apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service_with_docs
  description: The place to be, for great artists
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: backstage/demo
spec:
  type: service
  lifecycle: production
  owner: zi-yang
  system: public-websites
